allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.9'
  - '@expo/metro-config@57.0.6'
  - '@expo/metro-runtime@57.0.6'
  - '@expo/prebuild-config@57.0.8'
  - expo-asset@57.0.6
  - expo-constants@57.0.6
  - expo-modules-autolinking@57.0.8
  - expo-modules-core@57.0.6
  - expo@57.0.7
