// Generate assets from checked-in artwork; rendering React to SVG flattens animation.
import { readFile, writeFile, mkdir } from 'node:fs/promises';
const project=new URL('../../',import.meta.url);
const intro=JSON.parse(await readFile(new URL('src/domain/brandIntro.json',project),'utf8'));
let base=await readFile(new URL('web/src/assets/splash-map.svg',project),'utf8');
for(const step of intro.steps){
  const start=`<g transform="translate(${step.x},${step.y}) rotate(${step.rotation})">`;
  const offset=base.indexOf(start),end=base.indexOf('</g>',offset);
  if(offset<0||end<0)throw Error('Original footprint missing');
  base=base.slice(0,offset)+base.slice(end+4);
}
const v=intro.viewport;
base=base.replace('viewBox="0 0 320 560"',`viewBox="${v.x} ${v.y} ${v.width} ${v.height}"`);
if(!base.includes('id="jeonnam-boundary"')||base.includes('rotate(-22)'))throw Error('Static map extraction failed');
const assets=new URL('android-native/app/src/main/assets/',project);
await mkdir(assets,{recursive:true});
await writeFile(new URL('web/src/assets/splash-map-base.svg',project),base);
await writeFile(new URL('web_splash_map.svg',assets),base);
await writeFile(new URL('PRETENDARD-LICENSE.txt',assets),await readFile(new URL('android-native/PRETENDARD-LICENSE.txt',project)));
const kotlin=`// Generated by tools/sync-web-art.mjs from src/domain/brandIntro.json.\npackage kr.co.waboranggae.nativepilot.ui\n\ndata class IntroStep(val x:Float,val y:Float,val rotation:Float,val right:Boolean,val delayMs:Int)\nobject BrandIntroSpec {\n    const val durationMs=${intro.durationMs}\n    const val stepDurationMs=${intro.stepDurationMs}\n    const val x=${v.x}f\n    const val y=${v.y}f\n    const val width=${v.width}f\n    const val height=${v.height}f\n    val steps=listOf(\n${intro.steps.map(s=>`        IntroStep(${s.x}f,${s.y}f,${s.rotation}f,${s.right},${s.delayMs})`).join(',\n')}\n    )\n}\n`;
await writeFile(new URL('android-native/app/src/main/java/kr/co/waboranggae/nativepilot/ui/BrandIntroSpec.kt',project),kotlin);
console.log('Synced actual Jeonnam map and shared six-step animation timing; no network access.');
