import {publicPrivacyHtml} from '../../src/domain/privacyPolicy';
import {publicServiceTermsHtml} from '../../src/domain/serviceTerms';
import {PRIVACY_OPERATOR_NAME,SUPPORT_EMAIL} from '../../src/domain/privacyNotice';
const style="body{margin:0;background:#f4f5f3;color:#1c1c1e;font:16px/1.8 system-ui,sans-serif}main{max-width:820px;margin:auto;padding:48px 24px}h1{font-size:44px;letter-spacing:-2px}h2{margin-top:36px;font-size:22px}a{color:#176047}header{background:#183d31;color:white;border-radius:28px;padding:28px}nav{display:flex;gap:20px;flex-wrap:wrap;margin:24px 0}p,li{overflow-wrap:anywhere}footer{margin-top:40px;color:#646966;font-size:13px}section{background:white;padding:24px;border-radius:24px;margin:18px 0}";
export function publicAppPage(request:Request){
  const path=new URL(request.url).pathname;
  const privacy=path==='/app/privacy',terms=path==='/app/terms',remove=path==='/app/delete-account';
  const title=privacy?'개인정보처리방침':terms?'서비스 이용약관':remove?'계정 탈퇴 안내':'전남 뚜벅이 여행';
  const body=privacy?publicPrivacyHtml():terms?publicServiceTermsHtml():remove?`<h2>앱에서 탈퇴하기</h2><p>내 여행 → 계정 탈퇴에서 계정과 저장 코스를 삭제할 수 있습니다.</p><h2>앱을 사용할 수 없는 경우</h2><p><a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a>로 삭제를 요청해 주세요. 사용하는 로그인 방식과 계정 이메일 또는 닉네임을 알려주시면 필요한 본인 확인 방법을 안내합니다. 비밀번호·인증번호는 보내지 마세요.</p><p>앱 계정 삭제는 카카오·Google 계정 자체의 삭제가 아닙니다. 저장한 코스와 앱 내 계정 연결 정보는 삭제되어 복구할 수 없습니다.</p>`:
    '<section><h2>차 없이도, 나다운 전남 여행</h2><p>뚜버기는 전남의 여행지와 음식점을 살펴보고 도보·대중교통 이동을 고려한 코스를 만드는 Android 앱입니다.</p></section><section><h2>날짜와 취향을 고르고</h2><p>당일 여행부터 여러 날 여행까지. 날짜별 시간과 여행 목적·식사 조건에 맞춰 일정을 살펴보세요.</p><h2>코스를 내 방식으로</h2><p>장소를 추가하거나 순서를 바꾸고, 지도에서 동선을 확인할 수 있습니다. 로그인하면 원하는 코스를 저장할 수 있습니다.</p></section><p>현재 원스토어 출시 준비 중입니다. 이동·날씨 정보는 제공 시점과 현장 상황에 따라 달라질 수 있습니다.</p>';
  const html=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>뚜버기 · ${title}</title><meta name="description" content="뚜버기: 전남 도보·대중교통 여행 코스"><style>${style}</style></head><body><main><header><h1>뚜버기</h1><p>${title}</p></header><nav><a href="/app">앱 소개</a><a href="/app/terms">서비스 이용약관</a><a href="/app/privacy">개인정보처리방침</a><a href="/app/delete-account">계정 탈퇴 안내</a></nav>${body}<footer>${PRIVACY_OPERATOR_NAME}<br>문의: <a href="mailto:${SUPPORT_EMAIL}">${SUPPORT_EMAIL}</a></footer></main></body></html>`;
  return new Response(request.method==='HEAD'?null:html,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'public, max-age=300','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'",'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Permissions-Policy':'geolocation=(), camera=(), microphone=()'}});
}
