// Generated by tools/sync-web-art.mjs from src/domain/brandIntro.json.
package kr.co.waboranggae.nativepilot.ui

data class IntroStep(val x:Float,val y:Float,val rotation:Float,val right:Boolean,val delayMs:Int)
object BrandIntroSpec {
    const val durationMs=2800
    const val stepDurationMs=1100
    const val x=8f
    const val y=64f
    const val width=272f
    const val height=380f
    val steps=listOf(
        IntroStep(28f,420f,-22f,false,400),
        IntroStep(52f,392f,-22f,true,620),
        IntroStep(74f,362f,-22f,false,840),
        IntroStep(98f,332f,-22f,true,1060),
        IntroStep(118f,300f,-22f,false,1280),
        IntroStep(140f,270f,-22f,true,1500)
    )
}
